// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fastSwarm
NumericVector fastSwarm(NumericVector x, LogicalVector compact);
RcppExport SEXP _beeswarm_fastSwarm(SEXP xSEXP, SEXP compactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type compact(compactSEXP);
    rcpp_result_gen = Rcpp::wrap(fastSwarm(x, compact));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _beeswarm_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_beeswarm_fastSwarm", (DL_FUNC) &_beeswarm_fastSwarm, 2},
    {"_beeswarm_rcpp_hello", (DL_FUNC) &_beeswarm_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_beeswarm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
