# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastSwarm <- function(x, compact) {
    .Call(`_beeswarm_fastSwarm`, x, compact)
}

rcpp_hello <- function() {
    .Call(`_beeswarm_rcpp_hello`)
}

